pipeline {
    agent any

    parameters {
        string(name: 'AWS_ACCESS_KEY_ID', description: 'Enter AWS Access Key ID')
        password(name: 'AWS_SECRET_ACCESS_KEY', description: 'Enter AWS Secret Access Key')
        string(name: 'AWS_REGION', defaultValue: 'us-east-1', description: 'Enter AWS Region')
    }

    environment {
        TF_VERSION = "1.6.6"
    }

    stages {

        stage('Git Clone') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/mygithubco/Newterraform-repo.git'
            }
        }

        stage('Check & Install AWS CLI') {
            steps {
                sh '''
                    if command -v aws >/dev/null 2>&1; then
                        echo "AWS CLI already installed"
                    else
                        echo "Installing AWS CLI..."
                        sudo apt update
                        sudo apt install -y unzip curl
                        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
                        unzip awscliv2.zip
                        sudo ./aws/install
                    fi
                    aws --version
                '''
            }
        }

        stage('Check & Install Terraform') {
            steps {
                sh '''
                    if command -v terraform >/dev/null 2>&1; then
                        echo "Terraform already installed"
                    else
                        echo "Installing Terraform..."
                        sudo apt update
                        sudo apt install -y wget unzip
                        wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
                        unzip terraform_${TF_VERSION}_linux_amd64.zip
                        sudo mv terraform /usr/local/bin/
                    fi
                    terraform version
                '''
            }
        }

        stage('Set AWS Credentials') {
            steps {
                sh '''
                    export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
                    export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
                    export AWS_DEFAULT_REGION=${AWS_REGION}

                    aws sts get-caller-identity
                '''
            }
        }

        stage('Create S3 Backend & DynamoDB Lock') {
            steps {
                sh '''
                    aws s3api create-bucket \
                        --bucket my-terraform-backend-jenkins \
                        --region ${AWS_REGION} \
                        --create-bucket-configuration LocationConstraint=${AWS_REGION} \
                        || echo "S3 bucket already exists"

                    aws s3api put-bucket-versioning \
                        --bucket my-terraform-backend-jenkins \
                        --versioning-configuration Status=Enabled

                    aws dynamodb create-table \
                        --table-name terraform-lock-table \
                        --attribute-definitions AttributeName=LockID,AttributeType=S \
                        --key-schema AttributeName=LockID,KeyType=HASH \
                        --billing-mode PAY_PER_REQUEST \
                        || echo "DynamoDB table already exists"
                '''
            }
        }

        stage('Terraform Init') {
            steps {
                sh 'terraform init'
            }
        }

        stage('Terraform Plan') {
            steps {
                sh 'terraform plan -out=tfplan'
            }
        }

        stage('Terraform Apply') {
            steps {
                sh 'terraform apply -auto-approve tfplan'
            }
        }
    }

    post {
        success {
            echo "Terraform deployment completed successfully"
        }
        failure {
            echo "Terraform deployment failed"
        }
    }
}
